version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: "-g 0 -l 9999999999999999999999999999 --account=\"0x348ce564d427a3311b6536bbcff9390d69395b06ed6c486954e971d960fe8709,0xFFFFFFFFFFFFFFFF\""
    ports:
      - "8545:8545"
    restart: unless-stopped

  proxy:
    build:
      dockerfile: ./docker/containers/Functions/Dockerfile
      context: ../../../
    depends_on:
      - ganache
    ports:
     - "8585:80"
    restart: unless-stopped
    environment:
      - RPC_URL=http://ganache:8545
      - BLOB_CONTAINER_NAME=${BLOB_CONTRACT_CONTAINER_NAME}
      - BLOB_CONNECT_STR=${BLOB_CONNECT_STR}
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
